version: "3"
services:
  api:
    build: .
    image: ui_test:latest
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres
    environment:
      - NODE_ENV=production

  postgres:
    container_name: postgres
    image: postgres:14.1-alpine
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ui_test"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: ui_test
      POSTGRES_DB: ui_test
      POSTGRES_PASSWORD: password
